# Generated by Django 4.1.6 on 2023-04-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='RegModel',
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='SModel',
        ),
    ]
