# Generated by Django 4.1.6 on 2023-04-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_register_regmodel_rename_status_smodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SModel',
            new_name='Marital',
        ),
        migrations.RenameModel(
            old_name='RegModel',
            new_name='Profile',
        ),
    ]
